### ISSUE TITLE
游戏内部输入!!qb出现乱码，后台输入正常

### ISSUE THREAD

**Issue by starhush** [TISUnion/QuickBackupM#57]
如图：
![bb22ba6d788f2fc5481a517ac8183a82](https://github.com/TISUnion/QuickBackupM/assets/132283814/e864f11b-50a8-470d-bf11-ca5d6b109905)
游戏内聊天框输入!!qb后出现的是乱码
同时后台输出如下：
![5208c3d58d9c327113e775601365b503](https://github.com/TISUnion/QuickBackupM/assets/132283814/7c2b4994-6e1f-4a56-925b-20b62abdfe80)
在此之后我进行了插件重装（同时删除qb_multi和config内的配置文件，并对服务器进行重启）发现游戏内还是乱码
![image](https://github.com/TISUnion/QuickBackupM/assets/132283814/2ec0e962-70bd-4b6f-b593-0feaff0689ad)
后台输出如下
![image](https://github.com/TISUnion/QuickBackupM/assets/132283814/4aeb6ae0-70ff-4869-b3e5-809d41e1c5d2)
值得注意的是在后台直接输入!!qb是没有问题的
![image](https://github.com/TISUnion/QuickBackupM/assets/132283814/89f3045b-a564-4c07-b4be-ca0008dc464c)
![image](https://github.com/TISUnion/QuickBackupM/assets/132283814/0ce956f1-ebe9-4b13-aa72-846b7bf818f2)
而且也是可以正常进行备份的
游戏内玩家能看到的只有这三条提示
![image](https://github.com/TISUnion/QuickBackupM/assets/132283814/09e6dc6c-aad5-4cf6-a738-59d54ee1f67d)

**Comment by shenjackyuanjie** [comment]
你的mcdr编码配置需要改吧

**Comment by starhush** [comment]
> 你的mcdr编码配置需要改吧

服务器也有其他MCDR的插件，服务器对话框显示都是正常的，就这个出了问题，如果是你说的这样应该集体出现相同问题吧。
mcdr编码配置我也不会搞，如果你会的话可否给下教程，我去试试

**Comment by shenjackyuanjie** [comment]
🤔
试试这个？
```yaml
# the encoding / decoding format used to encode / decode message to the server. Choose the best method for your os. Examples:
#   utf8
#   gbk
# leave it blank for MCDR to auto detect system encoding
encoding: utf8
decoding: gbk
```
